[project]
name = "fpl-frontend"
version = "0.1.0"
description = "Streamlit UI for FPL Cheat"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "streamlit>=1.38",
  "requests>=2.32",
  "python-dotenv>=1.0",
]

[tool.uv]
dev-dependencies = []

